-- 문제 : 입양시각 구하기(1)
-- 링크 : https://programmers.co.kr/learn/courses/30/lessons/59412

SELECT 
    TO_NUMBER(LTRIM(TO_CHAR(DATETIME,'HH24'),'0')) AS "HOUR"
    , COUNT(TO_CHAR(DATETIME,'HH')) AS "COUNT"
FROM ANIMAL_OUTS 
WHERE TO_NUMBER(LTRIM(TO_CHAR(DATETIME,'HH24'),'0')) BETWEEN 9 AND 20
GROUP BY TO_CHAR(DATETIME,'HH24')
ORDER BY 1;